"""empty message

Revision ID: 219ad6c027dd
Revises: 4d1a064b1423
Create Date: 2022-08-23 09:57:59.121737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219ad6c027dd'
down_revision = '4d1a064b1423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    # ### end Alembic commands ###
